
version: '3.9'

services:

  # Flask Application Container
  app:

    # Build image using Dockerfile
    build: .

    # Container name
    container_name: knowledge-intelligence-system

    # Map local port 8080 to container port 8080
    ports:
      - "8080:8080"

    # Load environment variables
    env_file:
      - app/.env

    # Start MinIO first
    depends_on:
      - minio

  # MinIO Storage Container
  minio:

    # Official MinIO image
    image: minio/minio

    # Container name
    container_name: minio

    # Start MinIO server
    command: server /data --console-address ":9001"

    # Login credentials
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123

    # Expose ports
    ports:
      - "9000:9000"
      - "9001:9001"

    # Persistent storage
    volumes:
      - minio_data:/data

# Docker volume
volumes:
  minio_data:
